### PR TITLE
django 1.9 GenericForeignKey

### PR DESCRIPTION
**Pull request by 7wonders**

### CODE REVIEW

**Comment by czpython** [comment]
Hi there, thanks for the fix.
Unfortunately this would break compatibility with Django 1.6, please use a try/except in order to keep backwards compatibility.

**Comment by wsantos** [comment]
@czpython any plan to accept this ?

**Comment by czpython** [comment]
@wsantos Yes. It just needs to be rebased with the latest master.

**Comment by wsantos** [comment]
@czpython I'll create a new PR for it.

**Comment by czpython** [comment]
Closed by https://github.com/divio/django-mailchimp/pull/59

**Pull request closed without merging**
